name: Build & Test

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: cmake -B build -DWIN_UTILS_AUTOSTART_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir build --output-on-failure -C ${{ matrix.build_type }}
